version: '3'
services:
  flask-api-starter:
    build: .
    ports:
      - "8000:5000"
    env_file: .env
    links:
      - postgres:postgres
    restart: always
  postgres:
    image: "postgres:12.0-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env-postgres
    restart: always
volumes:
  postgres_data: